name: flutter_dev_test
description: "Developer's Flutter test"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  otp: ^3.1.4
  equatable: ^2.0.5
  dartz: ^0.10.1
  http: ^1.2.2
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  go_router: ^14.3.0
  get_it: ^8.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  #flutter pub run import_sorter:main
  import_sorter: ^4.6.0
  test: ^1.25.8
  bloc_test: ^9.1.7
  mockito: ^5.4.4
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

  assets:
    - assets/login_image.png
